/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StaticRouteRouteImport } from './routes/_static/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCitiesIndexRouteImport } from './routes/api/cities/index'
import { Route as StaticDocsIndexRouteImport } from './routes/_static/docs/index'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as StaticDocsNameRouteImport } from './routes/_static/docs/$name'
import { Route as ApiCitiesCityIdStreetsRouteImport } from './routes/api/cities/$cityId/streets'
import { Route as AuthAppPolarSubscriptionsRouteImport } from './routes/_auth/app/polar/subscriptions'
import { Route as AuthAppPolarPortalRouteImport } from './routes/_auth/app/polar/portal'
import { Route as AuthAppPolarCheckoutSuccessRouteImport } from './routes/_auth/app/polar/checkout.success'

const StaticRouteRoute = StaticRouteRouteImport.update({
  id: '/_static',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCitiesIndexRoute = ApiCitiesIndexRouteImport.update({
  id: '/api/cities/',
  path: '/api/cities/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaticDocsIndexRoute = StaticDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => StaticRouteRoute,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const StaticDocsNameRoute = StaticDocsNameRouteImport.update({
  id: '/docs/$name',
  path: '/docs/$name',
  getParentRoute: () => StaticRouteRoute,
} as any)
const ApiCitiesCityIdStreetsRoute = ApiCitiesCityIdStreetsRouteImport.update({
  id: '/api/cities/$cityId/streets',
  path: '/api/cities/$cityId/streets',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppPolarSubscriptionsRoute =
  AuthAppPolarSubscriptionsRouteImport.update({
    id: '/app/polar/subscriptions',
    path: '/app/polar/subscriptions',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthAppPolarPortalRoute = AuthAppPolarPortalRouteImport.update({
  id: '/app/polar/portal',
  path: '/app/polar/portal',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppPolarCheckoutSuccessRoute =
  AuthAppPolarCheckoutSuccessRouteImport.update({
    id: '/app/polar/checkout/success',
    path: '/app/polar/checkout/success',
    getParentRoute: () => AuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs/$name': typeof StaticDocsNameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AuthAppIndexRoute
  '/docs': typeof StaticDocsIndexRoute
  '/api/cities': typeof ApiCitiesIndexRoute
  '/app/polar/portal': typeof AuthAppPolarPortalRoute
  '/app/polar/subscriptions': typeof AuthAppPolarSubscriptionsRoute
  '/api/cities/$cityId/streets': typeof ApiCitiesCityIdStreetsRoute
  '/app/polar/checkout/success': typeof AuthAppPolarCheckoutSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/$name': typeof StaticDocsNameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AuthAppIndexRoute
  '/docs': typeof StaticDocsIndexRoute
  '/api/cities': typeof ApiCitiesIndexRoute
  '/app/polar/portal': typeof AuthAppPolarPortalRoute
  '/app/polar/subscriptions': typeof AuthAppPolarSubscriptionsRoute
  '/api/cities/$cityId/streets': typeof ApiCitiesCityIdStreetsRoute
  '/app/polar/checkout/success': typeof AuthAppPolarCheckoutSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_static': typeof StaticRouteRouteWithChildren
  '/_static/docs/$name': typeof StaticDocsNameRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_static/docs/': typeof StaticDocsIndexRoute
  '/api/cities/': typeof ApiCitiesIndexRoute
  '/_auth/app/polar/portal': typeof AuthAppPolarPortalRoute
  '/_auth/app/polar/subscriptions': typeof AuthAppPolarSubscriptionsRoute
  '/api/cities/$cityId/streets': typeof ApiCitiesCityIdStreetsRoute
  '/_auth/app/polar/checkout/success': typeof AuthAppPolarCheckoutSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs/$name'
    | '/api/auth/$'
    | '/app'
    | '/docs'
    | '/api/cities'
    | '/app/polar/portal'
    | '/app/polar/subscriptions'
    | '/api/cities/$cityId/streets'
    | '/app/polar/checkout/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/$name'
    | '/api/auth/$'
    | '/app'
    | '/docs'
    | '/api/cities'
    | '/app/polar/portal'
    | '/app/polar/subscriptions'
    | '/api/cities/$cityId/streets'
    | '/app/polar/checkout/success'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_static'
    | '/_static/docs/$name'
    | '/api/auth/$'
    | '/_auth/app/'
    | '/_static/docs/'
    | '/api/cities/'
    | '/_auth/app/polar/portal'
    | '/_auth/app/polar/subscriptions'
    | '/api/cities/$cityId/streets'
    | '/_auth/app/polar/checkout/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  StaticRouteRoute: typeof StaticRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiCitiesIndexRoute: typeof ApiCitiesIndexRoute
  ApiCitiesCityIdStreetsRoute: typeof ApiCitiesCityIdStreetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_static': {
      id: '/_static'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof StaticRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cities/': {
      id: '/api/cities/'
      path: '/api/cities'
      fullPath: '/api/cities'
      preLoaderRoute: typeof ApiCitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_static/docs/': {
      id: '/_static/docs/'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof StaticDocsIndexRouteImport
      parentRoute: typeof StaticRouteRoute
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_static/docs/$name': {
      id: '/_static/docs/$name'
      path: '/docs/$name'
      fullPath: '/docs/$name'
      preLoaderRoute: typeof StaticDocsNameRouteImport
      parentRoute: typeof StaticRouteRoute
    }
    '/api/cities/$cityId/streets': {
      id: '/api/cities/$cityId/streets'
      path: '/api/cities/$cityId/streets'
      fullPath: '/api/cities/$cityId/streets'
      preLoaderRoute: typeof ApiCitiesCityIdStreetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/polar/subscriptions': {
      id: '/_auth/app/polar/subscriptions'
      path: '/app/polar/subscriptions'
      fullPath: '/app/polar/subscriptions'
      preLoaderRoute: typeof AuthAppPolarSubscriptionsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/polar/portal': {
      id: '/_auth/app/polar/portal'
      path: '/app/polar/portal'
      fullPath: '/app/polar/portal'
      preLoaderRoute: typeof AuthAppPolarPortalRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/polar/checkout/success': {
      id: '/_auth/app/polar/checkout/success'
      path: '/app/polar/checkout/success'
      fullPath: '/app/polar/checkout/success'
      preLoaderRoute: typeof AuthAppPolarCheckoutSuccessRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAppIndexRoute: typeof AuthAppIndexRoute
  AuthAppPolarPortalRoute: typeof AuthAppPolarPortalRoute
  AuthAppPolarSubscriptionsRoute: typeof AuthAppPolarSubscriptionsRoute
  AuthAppPolarCheckoutSuccessRoute: typeof AuthAppPolarCheckoutSuccessRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppIndexRoute: AuthAppIndexRoute,
  AuthAppPolarPortalRoute: AuthAppPolarPortalRoute,
  AuthAppPolarSubscriptionsRoute: AuthAppPolarSubscriptionsRoute,
  AuthAppPolarCheckoutSuccessRoute: AuthAppPolarCheckoutSuccessRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface StaticRouteRouteChildren {
  StaticDocsNameRoute: typeof StaticDocsNameRoute
  StaticDocsIndexRoute: typeof StaticDocsIndexRoute
}

const StaticRouteRouteChildren: StaticRouteRouteChildren = {
  StaticDocsNameRoute: StaticDocsNameRoute,
  StaticDocsIndexRoute: StaticDocsIndexRoute,
}

const StaticRouteRouteWithChildren = StaticRouteRoute._addFileChildren(
  StaticRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  StaticRouteRoute: StaticRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiCitiesIndexRoute: ApiCitiesIndexRoute,
  ApiCitiesCityIdStreetsRoute: ApiCitiesCityIdStreetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
