/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as ApiUserHasCredentialAccountRouteImport } from './routes/api/user/has-credential-account'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthAppSourcesIndexRouteImport } from './routes/_auth/app/sources/index'
import { Route as AuthAppSourcesNewRouteImport } from './routes/_auth/app/sources/new'
import { Route as AuthAppSourcesSourceIdEditRouteImport } from './routes/_auth/app/sources/$sourceId.edit'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiUserHasCredentialAccountRoute =
  ApiUserHasCredentialAccountRouteImport.update({
    id: '/api/user/has-credential-account',
    path: '/api/user/has-credential-account',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppSourcesIndexRoute = AuthAppSourcesIndexRouteImport.update({
  id: '/app/sources/',
  path: '/app/sources/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppSourcesNewRoute = AuthAppSourcesNewRouteImport.update({
  id: '/app/sources/new',
  path: '/app/sources/new',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppSourcesSourceIdEditRoute =
  AuthAppSourcesSourceIdEditRouteImport.update({
    id: '/app/sources/$sourceId/edit',
    path: '/app/sources/$sourceId/edit',
    getParentRoute: () => AuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/legal': typeof LegalRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/user/has-credential-account': typeof ApiUserHasCredentialAccountRoute
  '/app/': typeof AuthAppIndexRoute
  '/app/sources/new': typeof AuthAppSourcesNewRoute
  '/app/sources/': typeof AuthAppSourcesIndexRoute
  '/app/sources/$sourceId/edit': typeof AuthAppSourcesSourceIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/legal': typeof LegalRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/user/has-credential-account': typeof ApiUserHasCredentialAccountRoute
  '/app': typeof AuthAppIndexRoute
  '/app/sources/new': typeof AuthAppSourcesNewRoute
  '/app/sources': typeof AuthAppSourcesIndexRoute
  '/app/sources/$sourceId/edit': typeof AuthAppSourcesSourceIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/cookie-policy': typeof CookiePolicyRoute
  '/legal': typeof LegalRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/user/has-credential-account': typeof ApiUserHasCredentialAccountRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/_auth/app/sources/new': typeof AuthAppSourcesNewRoute
  '/_auth/app/sources/': typeof AuthAppSourcesIndexRoute
  '/_auth/app/sources/$sourceId/edit': typeof AuthAppSourcesSourceIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookie-policy'
    | '/legal'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/auth/login'
    | '/auth/register'
    | '/api/auth/$'
    | '/api/user/has-credential-account'
    | '/app/'
    | '/app/sources/new'
    | '/app/sources/'
    | '/app/sources/$sourceId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookie-policy'
    | '/legal'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/auth/login'
    | '/auth/register'
    | '/api/auth/$'
    | '/api/user/has-credential-account'
    | '/app'
    | '/app/sources/new'
    | '/app/sources'
    | '/app/sources/$sourceId/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/cookie-policy'
    | '/legal'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/auth/login'
    | '/auth/register'
    | '/api/auth/$'
    | '/api/user/has-credential-account'
    | '/_auth/app/'
    | '/_auth/app/sources/new'
    | '/_auth/app/sources/'
    | '/_auth/app/sources/$sourceId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  CookiePolicyRoute: typeof CookiePolicyRoute
  LegalRoute: typeof LegalRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiUserHasCredentialAccountRoute: typeof ApiUserHasCredentialAccountRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/user/has-credential-account': {
      id: '/api/user/has-credential-account'
      path: '/api/user/has-credential-account'
      fullPath: '/api/user/has-credential-account'
      preLoaderRoute: typeof ApiUserHasCredentialAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/sources/': {
      id: '/_auth/app/sources/'
      path: '/app/sources'
      fullPath: '/app/sources/'
      preLoaderRoute: typeof AuthAppSourcesIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/sources/new': {
      id: '/_auth/app/sources/new'
      path: '/app/sources/new'
      fullPath: '/app/sources/new'
      preLoaderRoute: typeof AuthAppSourcesNewRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/sources/$sourceId/edit': {
      id: '/_auth/app/sources/$sourceId/edit'
      path: '/app/sources/$sourceId/edit'
      fullPath: '/app/sources/$sourceId/edit'
      preLoaderRoute: typeof AuthAppSourcesSourceIdEditRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAppIndexRoute: typeof AuthAppIndexRoute
  AuthAppSourcesNewRoute: typeof AuthAppSourcesNewRoute
  AuthAppSourcesIndexRoute: typeof AuthAppSourcesIndexRoute
  AuthAppSourcesSourceIdEditRoute: typeof AuthAppSourcesSourceIdEditRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppIndexRoute: AuthAppIndexRoute,
  AuthAppSourcesNewRoute: AuthAppSourcesNewRoute,
  AuthAppSourcesIndexRoute: AuthAppSourcesIndexRoute,
  AuthAppSourcesSourceIdEditRoute: AuthAppSourcesSourceIdEditRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  CookiePolicyRoute: CookiePolicyRoute,
  LegalRoute: LegalRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiUserHasCredentialAccountRoute: ApiUserHasCredentialAccountRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
