/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as ApiCitiesIndexRouteImport } from './routes/api/cities/index'
import { Route as AuthAppIndexRouteImport } from './routes/_auth/app/index'
import { Route as ApiUserHasCredentialAccountRouteImport } from './routes/api/user/has-credential-account'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as AuthAppPaymentSuccessRouteImport } from './routes/_auth/app/payment-success'
import { Route as AuthAppPaymentCancelRouteImport } from './routes/_auth/app/payment-cancel'
import { Route as ApiCitiesCityIdStreetsRouteImport } from './routes/api/cities/$cityId/streets'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCitiesIndexRoute = ApiCitiesIndexRouteImport.update({
  id: '/api/cities/',
  path: '/api/cities/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppIndexRoute = AuthAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiUserHasCredentialAccountRoute =
  ApiUserHasCredentialAccountRouteImport.update({
    id: '/api/user/has-credential-account',
    path: '/api/user/has-credential-account',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAppPaymentSuccessRoute = AuthAppPaymentSuccessRouteImport.update({
  id: '/app/payment-success',
  path: '/app/payment-success',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAppPaymentCancelRoute = AuthAppPaymentCancelRouteImport.update({
  id: '/app/payment-cancel',
  path: '/app/payment-cancel',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiCitiesCityIdStreetsRoute = ApiCitiesCityIdStreetsRouteImport.update({
  id: '/api/cities/$cityId/streets',
  path: '/api/cities/$cityId/streets',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/legal': typeof LegalRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/payment-cancel': typeof AuthAppPaymentCancelRoute
  '/app/payment-success': typeof AuthAppPaymentSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/user/has-credential-account': typeof ApiUserHasCredentialAccountRoute
  '/app': typeof AuthAppIndexRoute
  '/api/cities': typeof ApiCitiesIndexRoute
  '/api/cities/$cityId/streets': typeof ApiCitiesCityIdStreetsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/legal': typeof LegalRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/app/payment-cancel': typeof AuthAppPaymentCancelRoute
  '/app/payment-success': typeof AuthAppPaymentSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/user/has-credential-account': typeof ApiUserHasCredentialAccountRoute
  '/app': typeof AuthAppIndexRoute
  '/api/cities': typeof ApiCitiesIndexRoute
  '/api/cities/$cityId/streets': typeof ApiCitiesCityIdStreetsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/cookie-policy': typeof CookiePolicyRoute
  '/legal': typeof LegalRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_auth/app/payment-cancel': typeof AuthAppPaymentCancelRoute
  '/_auth/app/payment-success': typeof AuthAppPaymentSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/user/has-credential-account': typeof ApiUserHasCredentialAccountRoute
  '/_auth/app/': typeof AuthAppIndexRoute
  '/api/cities/': typeof ApiCitiesIndexRoute
  '/api/cities/$cityId/streets': typeof ApiCitiesCityIdStreetsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookie-policy'
    | '/legal'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/auth/login'
    | '/auth/register'
    | '/app/payment-cancel'
    | '/app/payment-success'
    | '/api/auth/$'
    | '/api/user/has-credential-account'
    | '/app'
    | '/api/cities'
    | '/api/cities/$cityId/streets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookie-policy'
    | '/legal'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/auth/login'
    | '/auth/register'
    | '/app/payment-cancel'
    | '/app/payment-success'
    | '/api/auth/$'
    | '/api/user/has-credential-account'
    | '/app'
    | '/api/cities'
    | '/api/cities/$cityId/streets'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/cookie-policy'
    | '/legal'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/auth/login'
    | '/auth/register'
    | '/_auth/app/payment-cancel'
    | '/_auth/app/payment-success'
    | '/api/auth/$'
    | '/api/user/has-credential-account'
    | '/_auth/app/'
    | '/api/cities/'
    | '/api/cities/$cityId/streets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  CookiePolicyRoute: typeof CookiePolicyRoute
  LegalRoute: typeof LegalRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiUserHasCredentialAccountRoute: typeof ApiUserHasCredentialAccountRoute
  ApiCitiesIndexRoute: typeof ApiCitiesIndexRoute
  ApiCitiesCityIdStreetsRoute: typeof ApiCitiesCityIdStreetsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cities/': {
      id: '/api/cities/'
      path: '/api/cities'
      fullPath: '/api/cities'
      preLoaderRoute: typeof ApiCitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/': {
      id: '/_auth/app/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/user/has-credential-account': {
      id: '/api/user/has-credential-account'
      path: '/api/user/has-credential-account'
      fullPath: '/api/user/has-credential-account'
      preLoaderRoute: typeof ApiUserHasCredentialAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/app/payment-success': {
      id: '/_auth/app/payment-success'
      path: '/app/payment-success'
      fullPath: '/app/payment-success'
      preLoaderRoute: typeof AuthAppPaymentSuccessRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/app/payment-cancel': {
      id: '/_auth/app/payment-cancel'
      path: '/app/payment-cancel'
      fullPath: '/app/payment-cancel'
      preLoaderRoute: typeof AuthAppPaymentCancelRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/cities/$cityId/streets': {
      id: '/api/cities/$cityId/streets'
      path: '/api/cities/$cityId/streets'
      fullPath: '/api/cities/$cityId/streets'
      preLoaderRoute: typeof ApiCitiesCityIdStreetsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAppPaymentCancelRoute: typeof AuthAppPaymentCancelRoute
  AuthAppPaymentSuccessRoute: typeof AuthAppPaymentSuccessRoute
  AuthAppIndexRoute: typeof AuthAppIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAppPaymentCancelRoute: AuthAppPaymentCancelRoute,
  AuthAppPaymentSuccessRoute: AuthAppPaymentSuccessRoute,
  AuthAppIndexRoute: AuthAppIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  CookiePolicyRoute: CookiePolicyRoute,
  LegalRoute: LegalRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiUserHasCredentialAccountRoute: ApiUserHasCredentialAccountRoute,
  ApiCitiesIndexRoute: ApiCitiesIndexRoute,
  ApiCitiesCityIdStreetsRoute: ApiCitiesCityIdStreetsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
